#!/usr/bin/env python
"""Скрипт для наповнення Firestore тестовими даними"""
import os
import sys
import django

# Налаштування Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'weapons_shop.settings')
django.setup()

from shop.firebase_models import Category, Product

def main():
    print('Створення тестових даних в Firebase Firestore...')
    
    # Створення категорій
    categories_data = [
        {'name': 'Вогнепальна зброя', 'slug': 'firearms', 'description': 'Пістолети, рушниці, карабіни'},
        {'name': 'Пневматична зброя', 'slug': 'pneumatic', 'description': 'Пневматичні пістолети та рушниці'},
        {'name': 'Холодна зброя', 'slug': 'cold-weapons', 'description': 'Ножі, мечі, кинджали'},
        {'name': 'Аксесуари', 'slug': 'accessories', 'description': 'Боєприпаси, кобури, оптика'},
    ]

    categories = {}
    for cat_data in categories_data:
        # Перевіряємо, чи категорія вже існує
        existing = Category.get_one(filters=[('slug', '==', cat_data['slug'])])
        if existing:
            categories[cat_data['slug']] = existing
            print(f'Категорія вже існує: {existing.name}')
        else:
            category = Category(**cat_data)
            category.save()
            categories[cat_data['slug']] = category
            print(f'✅ Створено категорію: {category.name}')

    # Створення товарів (40 товарів)
    products_data = [
        # Вогнепальна зброя (15 товарів)
        {
            'name': 'Пістолет Glock 17',
            'slug': 'glock-17',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Glock',
            'caliber': '9x19mm',
            'barrel_length': '114mm',
            'weight': '625g',
            'price': 25000.00,
            'stock': 5,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Надійний пістолет для самооборони та службового використання. Відмінна ергономіка та точність.',
        },
        {
            'name': 'Пістолет Glock 19',
            'slug': 'glock-19',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Glock',
            'caliber': '9x19mm',
            'barrel_length': '102mm',
            'weight': '595g',
            'price': 24000.00,
            'stock': 8,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Компактна версія Glock 17. Ідеальна для прихованого носіння.',
        },
        {
            'name': 'Рушниця Benelli M4',
            'slug': 'benelli-m4',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Benelli',
            'caliber': '12 калібр',
            'barrel_length': '470mm',
            'weight': '3.8kg',
            'price': 45000.00,
            'stock': 3,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Самозарядна рушниця для полювання та спорту. Відмінна надійність.',
        },
        {
            'name': 'Карабін AR-15',
            'slug': 'ar-15',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Colt',
            'caliber': '5.56x45mm',
            'barrel_length': '406mm',
            'weight': '3.2kg',
            'price': 38000.00,
            'stock': 4,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Надійний карабін для спортивної стрільби та полювання.',
        },
        {
            'name': 'Пістолет Beretta 92FS',
            'slug': 'beretta-92fs',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Beretta',
            'caliber': '9x19mm',
            'barrel_length': '125mm',
            'weight': '950g',
            'price': 28000.00,
            'stock': 6,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Класичний пістолет з відкритим курком. Відмінна точність.',
        },
        {
            'name': 'Револьвер Smith & Wesson 686',
            'slug': 'sw-686',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Smith & Wesson',
            'caliber': '.357 Magnum',
            'barrel_length': '102mm',
            'weight': '1.1kg',
            'price': 32000.00,
            'stock': 2,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Надійний револьвер для самооборони та спорту.',
        },
        {
            'name': 'Рушниця Remington 870',
            'slug': 'remington-870',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Remington',
            'caliber': '12 калібр',
            'barrel_length': '508mm',
            'weight': '3.2kg',
            'price': 22000.00,
            'stock': 7,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Класична помпова рушниця. Надійність перевірена часом.',
        },
        {
            'name': 'Пістолет Sig Sauer P226',
            'slug': 'sig-p226',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Sig Sauer',
            'caliber': '9x19mm',
            'barrel_length': '112mm',
            'weight': '830g',
            'price': 35000.00,
            'stock': 4,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Високоякісний пістолет для службового використання.',
        },
        {
            'name': 'Карабін AK-74',
            'slug': 'ak-74',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Kalashnikov',
            'caliber': '5.45x39mm',
            'barrel_length': '415mm',
            'weight': '3.3kg',
            'price': 42000.00,
            'stock': 3,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Надійний карабін з відмінною репутацією.',
        },
        {
            'name': 'Пістолет CZ 75',
            'slug': 'cz-75',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'CZ',
            'caliber': '9x19mm',
            'barrel_length': '120mm',
            'weight': '1kg',
            'price': 26000.00,
            'stock': 5,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Чеський пістолет з відмінною ергономікою.',
        },
        {
            'name': 'Рушниця Mossberg 500',
            'slug': 'mossberg-500',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Mossberg',
            'caliber': '12 калібр',
            'barrel_length': '508mm',
            'weight': '3.1kg',
            'price': 18000.00,
            'stock': 9,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Надійна помпова рушниця для полювання.',
        },
        {
            'name': 'Пістолет Walther PPK',
            'slug': 'walther-ppk',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Walther',
            'caliber': '.380 ACP',
            'barrel_length': '83mm',
            'weight': '550g',
            'price': 30000.00,
            'stock': 3,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Компактний пістолет для прихованого носіння.',
        },
        {
            'name': 'Револьвер Ruger GP100',
            'slug': 'ruger-gp100',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Ruger',
            'caliber': '.357 Magnum',
            'barrel_length': '102mm',
            'weight': '1.2kg',
            'price': 29000.00,
            'stock': 4,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Міцний револьвер для самооборони.',
        },
        {
            'name': 'Карабін Winchester Model 70',
            'slug': 'winchester-70',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Winchester',
            'caliber': '.308 Win',
            'barrel_length': '610mm',
            'weight': '3.6kg',
            'price': 48000.00,
            'stock': 2,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Точна гвинтівка для полювання.',
        },
        {
            'name': 'Пістолет HK USP',
            'slug': 'hk-usp',
            'category_id': categories['firearms'].id,
            'weapon_type': 'firearm',
            'manufacturer': 'Heckler & Koch',
            'caliber': '9x19mm',
            'barrel_length': '108mm',
            'weight': '748g',
            'price': 40000.00,
            'stock': 3,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Високоякісний німецький пістолет.',
        },
        
        # Пневматична зброя (10 товарів)
        {
            'name': 'Пневматичний пістолет Gamo PT-85',
            'slug': 'gamo-pt-85',
            'category_id': categories['pneumatic'].id,
            'weapon_type': 'pneumatic',
            'manufacturer': 'Gamo',
            'caliber': '4.5mm',
            'price': 3500.00,
            'stock': 10,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Пневматичний пістолет для тренувань та розваг.',
        },
        {
            'name': 'Пневматична рушниця Gamo Hunter 1250',
            'slug': 'gamo-hunter-1250',
            'category_id': categories['pneumatic'].id,
            'weapon_type': 'pneumatic',
            'manufacturer': 'Gamo',
            'caliber': '4.5mm',
            'price': 5500.00,
            'stock': 8,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Потужна пневматична рушниця для полювання на дрібну дичину.',
        },
        {
            'name': 'Пневматичний пістолет Umarex Walther PPQ',
            'slug': 'umarex-ppq',
            'category_id': categories['pneumatic'].id,
            'weapon_type': 'pneumatic',
            'manufacturer': 'Umarex',
            'caliber': '4.5mm',
            'price': 4200.00,
            'stock': 12,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Точна копія Walther PPQ для тренувань.',
        },
        {
            'name': 'Пневматична рушниця Crosman 2240',
            'slug': 'crosman-2240',
            'category_id': categories['pneumatic'].id,
            'weapon_type': 'pneumatic',
            'manufacturer': 'Crosman',
            'caliber': '5.5mm',
            'price': 2800.00,
            'stock': 15,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Надійна пневматична рушниця для початківців.',
        },
        {
            'name': 'Пневматичний пістолет Beretta 92FS',
            'slug': 'pneumatic-beretta-92',
            'category_id': categories['pneumatic'].id,
            'weapon_type': 'pneumatic',
            'manufacturer': 'Umarex',
            'caliber': '4.5mm',
            'price': 3800.00,
            'stock': 9,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Копія Beretta 92FS для тренувань.',
        },
        {
            'name': 'Пневматична рушниця Hatsan 125',
            'slug': 'hatsan-125',
            'category_id': categories['pneumatic'].id,
            'weapon_type': 'pneumatic',
            'manufacturer': 'Hatsan',
            'caliber': '5.5mm',
            'price': 6200.00,
            'stock': 6,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Потужна пружинно-поршнева рушниця.',
        },
        {
            'name': 'Пневматичний пістолет Glock 17 Gen4',
            'slug': 'pneumatic-glock-17',
            'category_id': categories['pneumatic'].id,
            'weapon_type': 'pneumatic',
            'manufacturer': 'Umarex',
            'caliber': '4.5mm',
            'price': 4500.00,
            'stock': 11,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Точна копія Glock 17 для тренувань.',
        },
        {
            'name': 'Пневматична рушниця Diana 350',
            'slug': 'diana-350',
            'category_id': categories['pneumatic'].id,
            'weapon_type': 'pneumatic',
            'manufacturer': 'Diana',
            'caliber': '4.5mm',
            'price': 4800.00,
            'stock': 7,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Німецька якість для точних пострілів.',
        },
        {
            'name': 'Пневматичний пістолет Sig Sauer P226',
            'slug': 'pneumatic-sig-p226',
            'category_id': categories['pneumatic'].id,
            'weapon_type': 'pneumatic',
            'manufacturer': 'Umarex',
            'caliber': '4.5mm',
            'price': 4000.00,
            'stock': 8,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Копія Sig Sauer P226 для тренувань.',
        },
        {
            'name': 'Пневматична рушниця Weihrauch HW100',
            'slug': 'weihrauch-hw100',
            'category_id': categories['pneumatic'].id,
            'weapon_type': 'pneumatic',
            'manufacturer': 'Weihrauch',
            'caliber': '4.5mm',
            'price': 8500.00,
            'stock': 4,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Премиум пневматична рушниця з PCP системою.',
        },
        
        # Холодна зброя (10 товарів)
        {
            'name': 'Ніж тактичний Cold Steel',
            'slug': 'cold-steel-tactical',
            'category_id': categories['cold-weapons'].id,
            'weapon_type': 'cold',
            'manufacturer': 'Cold Steel',
            'material': 'Нержавіюча сталь',
            'price': 2500.00,
            'stock': 15,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Надійний тактичний ніж для виживання.',
        },
        {
            'name': 'Ніж бойовий Ka-Bar',
            'slug': 'kabar-combat',
            'category_id': categories['cold-weapons'].id,
            'weapon_type': 'cold',
            'manufacturer': 'Ka-Bar',
            'material': 'Вуглецева сталь',
            'price': 3200.00,
            'stock': 8,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Класичний бойовий ніж з історією.',
        },
        {
            'name': 'Меч катана',
            'slug': 'katana-sword',
            'category_id': categories['cold-weapons'].id,
            'weapon_type': 'cold',
            'manufacturer': 'Traditional',
            'material': 'Вуглецева сталь',
            'price': 15000.00,
            'stock': 3,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Традиційний японський меч для колекціонування.',
        },
        {
            'name': 'Ніж виживання Gerber Bear Grylls',
            'slug': 'gerber-bear-grylls',
            'category_id': categories['cold-weapons'].id,
            'weapon_type': 'cold',
            'manufacturer': 'Gerber',
            'material': 'Нержавіюча сталь',
            'price': 2800.00,
            'stock': 12,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Універсальний ніж для виживання в екстремальних умовах.',
        },
        {
            'name': 'Кинджал тактичний',
            'slug': 'tactical-dagger',
            'category_id': categories['cold-weapons'].id,
            'weapon_type': 'cold',
            'manufacturer': 'Cold Steel',
            'material': 'Нержавіюча сталь',
            'price': 2200.00,
            'stock': 10,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Компактний кинджал для самооборони.',
        },
        {
            'name': 'Ніж складний Benchmade',
            'slug': 'benchmade-folder',
            'category_id': categories['cold-weapons'].id,
            'weapon_type': 'cold',
            'manufacturer': 'Benchmade',
            'material': 'Преміум сталь',
            'price': 4500.00,
            'stock': 6,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Високоякісний складний ніж з відмінною сталлю.',
        },
        {
            'name': 'Меч середньовічний',
            'slug': 'medieval-sword',
            'category_id': categories['cold-weapons'].id,
            'weapon_type': 'cold',
            'manufacturer': 'Windlass',
            'material': 'Вуглецева сталь',
            'price': 12000.00,
            'stock': 4,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Репліка середньовічного меча для колекціонування.',
        },
        {
            'name': 'Ніж полювання Buck',
            'slug': 'buck-hunting',
            'category_id': categories['cold-weapons'].id,
            'weapon_type': 'cold',
            'manufacturer': 'Buck Knives',
            'material': 'Нержавіюча сталь',
            'price': 3500.00,
            'stock': 9,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Надійний ніж для полювання та риболовлі.',
        },
        {
            'name': 'Сокира тактична',
            'slug': 'tactical-axe',
            'category_id': categories['cold-weapons'].id,
            'weapon_type': 'cold',
            'manufacturer': 'Cold Steel',
            'material': 'Вуглецева сталь',
            'price': 3800.00,
            'stock': 7,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Компактна тактична сокира для виживання.',
        },
        {
            'name': 'Ніж балисонг',
            'slug': 'balisong-knife',
            'category_id': categories['cold-weapons'].id,
            'weapon_type': 'cold',
            'manufacturer': 'Benchmade',
            'material': 'Нержавіюча сталь',
            'price': 5200.00,
            'stock': 5,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Філіппінський ніж-метелик для колекціонування.',
        },
        
        # Аксесуари (5 товарів)
        {
            'name': 'Кобура шкіряна',
            'slug': 'leather-holster',
            'category_id': categories['accessories'].id,
            'weapon_type': 'accessories',
            'manufacturer': 'Generic',
            'material': 'Шкіра',
            'price': 800.00,
            'stock': 20,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Якісна шкіряна кобура для пістолета.',
        },
        {
            'name': 'Кобура тактична Kydex',
            'slug': 'kydex-holster',
            'category_id': categories['accessories'].id,
            'weapon_type': 'accessories',
            'manufacturer': 'Safariland',
            'material': 'Kydex',
            'price': 1200.00,
            'stock': 15,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Сучасна тактична кобура з Kydex матеріалу.',
        },
        {
            'name': 'Приціл оптичний',
            'slug': 'optical-sight',
            'category_id': categories['accessories'].id,
            'weapon_type': 'accessories',
            'manufacturer': 'Vortex',
            'price': 8500.00,
            'stock': 8,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Якісний оптичний приціл для гвинтівок.',
        },
        {
            'name': 'Боєприпаси 9mm (100 шт)',
            'slug': 'ammo-9mm-100',
            'category_id': categories['accessories'].id,
            'weapon_type': 'accessories',
            'manufacturer': 'Federal',
            'caliber': '9x19mm',
            'price': 1200.00,
            'stock': 25,
            'is_popular': True,
            'is_active': True,
            'image': '',
            'description': 'Якісні боєприпаси для пістолетів калібру 9mm.',
        },
        {
            'name': 'Рюкзак тактичний',
            'slug': 'tactical-backpack',
            'category_id': categories['accessories'].id,
            'weapon_type': 'accessories',
            'manufacturer': '5.11 Tactical',
            'material': 'Нейлон',
            'price': 3500.00,
            'stock': 12,
            'is_popular': False,
            'is_active': True,
            'image': '',
            'description': 'Міцний тактичний рюкзак для обладнання.',
        },
    ]

    for prod_data in products_data:
        # Перевіряємо, чи товар вже існує
        existing = Product.get_one(filters=[('slug', '==', prod_data['slug'])])
        if existing:
            print(f'Товар вже існує: {existing.name}')
        else:
            product = Product(**prod_data)
            product.save()
            print(f'✅ Створено товар: {product.name}')

    print('\n✅ Тестові дані успішно створено в Firestore!')

if __name__ == '__main__':
    main()

